export type CreateTeachersInputDTO = {
  name: string | null;
  identity: string | null;
  document: string | null;
  dependents: number | null;
  birthAt: string | null;
  address: string | null;
  neighborhood: string | null;
  city: string | null;
  postalCode: string | null;
  phone: string | null;
  cellphone: string | null;
  email: string | null;
  observations: string | null;
  yearId: number;
  unitId: number;
  civilStatusId: number;
  positionId: number;
  disciplineId: number | null;
  situationId: number;
  speciality: string | null;
  remove: string | null;
  adido: string | null;
  readapted: string | null;
  readingRoom: string | null;
  computing: string | null;
  supplementCharge: string | null;
  tutoring: string | null;
  ambientalEducation: string | null;
  robotics: string | null;
  music: string | null;
};